name: Backend Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start backend services (Mongo + Server)
        run: docker compose up -d --build mongo server

      - name: Run backend tests inside container
        run: docker exec server npm test -- --ci --runInBand

      - name: Shut down backend services
        if: always()
        run: docker compose down
